### ISSUE TITLE
希望能够重视版权，尽快开源LaunchWrapper

### ISSUE THREAD

**Issue by dz-paji** [MinecraftChina/Forge#2]
你们在修改Forge源代码的同时还修改了Launchwrapper代码，目前还没有开源。希望尽快开源。
吐槽一下，这9个star是啥意思？还有一个fork？？？emmc？？？？真的搞不懂你网易，都把水军搞到github了

**Comment by ShieLian** [comment]
那一个fork应该是他们不会用git弄出来的，graph里什么都没有

**Comment by ZhangqianStudio** [comment]
哇，果然是大公司。员工连Git都不会用

**Comment by ShieLian** [comment]
理性怼人不要为怼而怼

**Comment by ZhangqianStudio** [comment]
你要是非这么想我也没办法

**Comment by ice1000** [comment]
其实fork的人不一定是这个意思，有可能是想自己维护一份和官方仓库有明确的diff列表的新仓库。如果猪厂的人真的良心到遵守开源协议，那么这种事情就是可以做到的。

然后就可以做一些别的骚事情了(应该是)

**Comment by ice1000** [comment]
还没看仓库，等会看下是不是上传配置文件和目标文件的git大牛搞的项目(雾

**Comment by ZhangqianStudio** [comment]
Emmc

**Comment by ice1000** [comment]
人家都会用branch功能了，已经不能算是萌新了

**Comment by mgdgfbhevdyeh** [comment]
branch功能算什么...一个大公司基本的git都不会，我服。

**Comment by ice1000** [comment]
哇 12个star了 我服 6啊 :joy:

**Comment by noc1793** [comment]
啥时候能弄完？

**Comment by noc1793** [comment]
暗中观察dalao的代码

**Comment by loveyanbei** [comment]
Mojang/LegacyLauncher 我没有找到版权声明，因此恐怕应该认为这部分代码属于mojang，网易怕是不会向外部公布修改的。

**Comment by mgdgfbhevdyeh** [comment]
但是Lex说要开源，而且Lex也是LaunchWrapper的维护者

**Comment by hutu13879513663** [comment]
LaunchWrapper 是啥？

**Comment by FledgeXu** [comment]
这就是网易对待开源的态度？就是所谓的“良心”网易？

**Comment by ice1000** [comment]
star 持续增长中 暗中观察.webp

**Comment by sjx233** [comment]
`dGhlcmUgc2hvdWxkIG5vdCBiZSBhbnkgc3RhcnM=`

**Comment by ZhangqianStudio** [comment]
agree with u

**Comment by ycwei982** [comment]
我都有些怀疑网易是不会用markdown？

**Comment by ice1000** [comment]
5bqU6K+l5Lq65a626L+Y5piv5Lya77yM5LiN55+l6YGT5LuW5Lus5YaF6YOo5oCB5bqm5ZKL5qC377yM54yq5Y6C5bqU6K+l5LiN57y66YKj56eN5b6I5Y6J5a6z55qE5byA5Y+R77yI5oiR6K6k6K+G55qE5LiA5Liq5b6I5Y6J5a6z55qE5Lq65bCx5Zyo54yq5Y6C5pCe5ri45oiP77yJ77yM5b6I5pyJ5Y+v6IO95piv5YW25LuW5Lq65ZGY55qE6ZSF77yI5LiN5oeC5oqA5pyv6L+Y6Z2e6KaBeGpi5pCe55qE6YKj56eN5by66KGM5Yi35a2Y5Zyo5oSf55qE

**Comment by ice1000** [comment]
`5ZOI5ZOI5L2g5Lus55qE5Lqk5rWB5pa55byP5aW95pyJ6Laj==`，学到了学到了

**Comment by lijun0326** [comment]
d2F0ZXIgYXJteeWTiOWTiOWTiOWTiOWTiOWTiOWTiA==

**Comment by sjx233** [comment]
@lijun0326 `dGhlIHdhdGVyIGFybXkgaXMg`[`aGVyZQ==`](https://github.com/MinecraftForge/MinecraftForge/issues/4185#issuecomment-316069571)

**Comment by RsWorkProgrammingGroup** [comment]
$1$9eJtDnb1$R7mZgCQHuLhWh1IREr3X9/

**Comment by ice1000** [comment]
已经变成水楼了，哈哈

**Comment by ycwei982** [comment]
因为网易mc部感觉基本不管GitHub，所以也没法因为Off Topic而Lock这接连几个issue

**Comment by Gary8682** [comment]
网易员工可都是国际C语言混乱代码大赛来的，你们还看不起

**Comment by ycwei982** [comment]
在中国不会几门语言都不敢叫程序员

**Comment by sjx233** [comment]
~IOCCC怎么了~

**Comment by GalvinGao** [comment]
`VGxWM2VWcDZWazFrV0UweFRsaEdSazVWZUhoaGVsWjVWakJKTVdOSFJURk9WMG8xVlVSV2FVNXJhekZqU0d4TFRtdDRhR0ZxVm1GVU1HeE1aRlprVldGVk9ISlBSM0JRVmpGU2NGUjVjelJpVTNSWVZrZHNVRlF3Um01YVYwWm9Za04wVkU1SVNteGhWelZ1WkZaa01tSnFTbk5rVm05eVZEQkdibVJWT1VKYU1tTTVVRkU5UFE9PQ==`

**Comment by sjx233** [comment]
@GalvinGao `VmpKMFUxTXlTWGRPVmxwcFVsZG9WMWx0ZUhkVE1WVjNXa1JTVG1KSVFraFdSM1JYWVZaYU5sSnFUbGhpVkVWM1ZGWmFUMDVzVW5WWGJYQlRVbXR3VDFkWGRHOVRhekZXVDFWV1RsSkVRVGs9`

**Comment by ycwei982** [comment]
Using base64 encoding is not fun

**Comment by ice1000** [comment]
Treat it as a joke

**Comment by zhourui123** [comment]
怎么感觉楼主会个git还带傲娇，会git你很牛吗，你生来就会git吗

**Comment by W192547975** [comment]
Ctrl+A，Ctrl+C，Ctrl+A，Ctrl+V，解码，Ctrl……
